spring:
  config:
    import: application-secret.yml

  mvc:
    path match:
      matching-strategy: ant_path_matcher

  datasource:
    url: jdbc:h2:file:./data/auth_db;MODE=MySQL
    driver-class-name: org.h2.Driver
    username: sa
    password:
    initialization-mode: never
    classpath: schema.sql

  h2:
    console:
      enabled: true
      path: /h2-console
mybatis:
    mapper-locations:
      - /mappers/*.xml

